apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  containers:
    - name: mycontainer
      image: redis
      volumeMounts:
        - name: "secrets"
          mountPath: "/etc/secrets"
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: "secrets"
      secret:
        secretName: "mysecret"
